REMOVE rule annotation processing code for docs
hacbs-contract/ec-policies pull request #294
Opened 2023-01-27 16:02 UTC by robnester-rh

Removed rule annotation processing code from the Antora extention.

Signed-off-by: Rob Nester <rnester@redhat.com>

2023-01-27 17:48 UTC, simonbaird requested changes
I think we need to keep most of this. The part that needs removing is just about the ruleData, which is line 132-136, and then there's some templating in `antora/docs/modules/ROOT/templates/_rules.hbs` for rendering the rule data.

2023-01-27 17:58 UTC, robnester-rh commented on antora/ec-policies-antora-extension/index.js
> -            shortName, title, description, anchor, ruleData, warningOrFailure,
ack

2023-01-30 11:58 UTC, zregvart approved these changes

2023-01-30 12:40 UTC, simonbaird approved these changes

2023-01-30 13:54 UTC, merged